apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: graf
spec:
  ports:
    - port: 3000
  selector:
    app: graf
  type: NodePort
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi   
