apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
template:
    metadata:
      name: grafana-deployment
      labels:
        app: grafana
    
    spec:
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
containers:
        - name: grafana-os
          image: ravi/grafana:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: grafana-storage